modLoader="javafml"
loaderVersion="[35.1,)" # 1.16.4 stable
issueTrackerURL="https://github.com/ramboxeu/techworks/issues"
showAsResourcePack=false
license="MIT"

[[mods]]
  modId="techworks"
  version="1.0.0.0"
  displayName="Techworks"
  displayURL="https://ramboxeu.github.io/projects/techworks"
  logoFile=""
  credits=""
  authors="Rambox"
  description='''
  Minecraft tech mod
  '''

[[dependencies.techworks]]
  modId="forge"
  mandatory=true
  versionRange="[32,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.techworks]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.16.4]"
  ordering="NONE"
  side="BOTH"